project:
  type: website

website:
  title: "AERME training session 2023"
  repo-url: https://ob7-ird.github.io/training_aerme_new/
  navbar:
    right:
      - href: index.qmd
        text: Home
      - text: Presentations
        menu:
          - href: materials/global_presentation.qmd
            text: "Introduction"
          - href: materials/role_play_presentation.qmd
            text: "Jeu de rôle"
    tools:
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/OB7-IRD/training_aerme_new
          - text: Report a Bug
            url: https://github.com/OB7-IRD/training_aerme_new/issues
  sidebar: 
    style: "docked"
    search: true
    contents: 
      - section: "Presentations"
        contents: 
          - materials/global_presentation.qmd
          - materials/role_play_presentation.qmd
  search: 
    location: navbar
    type: overlay

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
