---
format: 
  revealjs:
    target: "_blank"
    scrollable: true
    slide-number: c/t
    chalkboard: true 
    theme: template/theme_perso.scss
    logo: template/logo_ob7.png
    footer: "[https://github.com/OB7-IRD/training_aerme](https://github.com/OB7-IRD/training_aerme)"
editor: visual
---

# Jeu de rôle

## Simulation d'une réunion du RCG LP {.smaller}

-   Normalement réunion en anglais, la pour simplifier on passe en français
-   Contenu et aide disponible dans le repertoire "role_play_rcg" du [Github](https://github.com/OB7-IRD/training_aerme){target="_blank"} de la formation
-   Déroulement de la simualtion :
    -   Création des groupes et distribution des fiches d'identité de chaque pays - 5min
    -   Présentation du contexte, ouvertures et des éléments support pour vos discussions - 10min
    -   Discussion en groupe - 15min
    -   Discussions entre les participants - 30min
    -   Débriefing et comparaison avec la réalité - 30min

# Création des groupes et distribution des fiches d'identité de chaque pays

[5min]{style="color:#00a9d6; font-size: 1.5em"}

# Présentation du contexte, ouvertures et des éléments support pour vos discussions

[10min]{style="color:#00a9d6; font-size: 1.5em"}

## Contexte {.smaller}

-   [**RCG**]{style="color:#9a1c1f"} : "Regional Coordination Group", [groupe de coordination régional](https://www.fisheries-rcg.eu/){target="_blank"}
-   [**Objectifs**]{style="color:#9a1c1f"}
    -   améliorer la [**coordination**]{style="color:#9a1c1f"}, au sens large et au niveau [**européen**]{style="color:#9a1c1f"}, de le collecte de données associé aux pécheries
    -   Intermédiaire entre le niveau "[**national**]{style="color:#9a1c1f"}" et "[**internationnal**]{style="color:#9a1c1f"}"
    -   Passage d'une dynamique "[**nationale**]{style="color:#9a1c1f"}" à une dynamique "[**regionale**]{style="color:#9a1c1f"}"
-   6 actuellement en activité
    -   RCG NANSEA : Groupe de coordination régionale pour l'Atlantique Nord, la mer du Nord et l'Arctique oriental.
    -   RCG Baltic : Groupe de coordination régionale pour la Baltique.
    -   RCG Med&BS : Groupe de coordination régionale pour la Méditerranée et la mer Noire.
    -   RCG ECON : groupe de coordination régionale sur les questions économiques et groupe pan-régional qui s'occupent de la collecte de données socio-économiques.
    -   [**RCG LP**]{style="color:#9a1c1f"} : groupe de coordination régionale pour les grands pélagiques.
    -   RCG LDF : groupe de coordination régionale pour la pêche à longue distance.
-   [**Composé**]{style="color:#9a1c1f"} des pays européens concernés par la thématique, des utilisateurs finaux des données et des pays tiers

## Sujet

-   Votre objectif
    -   Trouver un [consensus]{style="color:#9a1c1f"} sur le développement d'une [base de données régionale]{style="color:#9a1c1f"} pour le RCG LP
    -   Pour simplifier on oublie tous les [aspects techniques]{style="color:#9a1c1f"} liée aux bases de données
-   Axe [principal]{style="color:#9a1c1f"}
    -   Volonté commune d'[avancer]{style="color:#9a1c1f"} sur le sujet
    -   N'oubliez pas d'être [bienveillant]{style="color:#9a1c1f"} et [constructifs]{style="color:#9a1c1f"} entre vous !

## Pour vous guider

### [Agenda de la réunion]{style="color:#00a9d6"}

-   Choix du système (RDBES/RDBFIS/Autre système)
-   Quels investissements humain et financier pour chaque pays ?
-   Plan d'action (court, moyen et long terme)
